$(function(){		
	$.easy.navigation();
	$.easy.tooltip();
	$.easy.popup();	
	$.easy.rotate();
	$.easy.cycle();
	$.easy.forms();
	$.easy.showhide();
	$.easy.jump();
	$.easy.tabs();
	$.easy.accordion();	
	//$.easy.external();
});